name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 2.0.5
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.19.4
  mocktail: ^0.2.0
  lints:
  path: ^1.8.0
  pointycastle: ^3.4.0
  build_runner: ^2.1.5
